version: build{build}

branches:
  only:
  - master
  - pre-release
  - dev

max_jobs: 1

# For Python versions available on Appveyor, see
# https://www.appveyor.com/docs/windows-images-software/#python
# https://www.appveyor.com/docs/linux-images-software#python
environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
      PYTHON: "C:\\Python38-x64\\python.exe"
      APPVEYOR_BAKE_IMAGE: vs2019_mathmakerlib
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu2004
      APPVEYOR_BAKE_IMAGE: ubuntu2004_mathmakerlib

install:
  # We need wheel installed to build wheels
  - sh: whoami
  - sh: pwd
  - sh: ls -alhG
  - cmd: set PYTHONIOENCODING=utf-8
  - cmd: set PY_PYTHON=3.8
  - cmd: set PATH=C:\\Python38-x64\\;C:\\Python38-x64\\Scripts;%USERPROFILE%\\AppData\\Roaming\\Python\\Scripts;%PATH%
  - cmd: python --version
  - cmd: python -c "import sys; print(sys.platform); print(sys.version_info)"
  - cmd: python -m venv py38
  - sh: sudo apt -qq update
  - sh: sudo apt -y install python3-venv python3-pip curl python-is-python3 fonts-ubuntu
  - sh: mkdir -p $HOME/.local/bin
  - sh: export PATH="$HOME/.local/bin:$PATH"
  - sh: echo $PATH
  - sh: curl https://gitlab.com/nicolas.hainaux/amoxtli/-/raw/master/src/olli/olli.sh > olli.sh
  - sh: chmod ugo+x olli.sh
  - sh: ./olli.sh linux
  - sh: wait $!
  - sh: export PATH="`cat $HOME/.tlbindir`:$PATH"
  - sh: echo $PATH
  - sh: lualatex --version
  - sh: luaotfload-tool --version

build_script:
  - cmd: .\py38\Scripts\activate.bat
  - cmd: curl -sSL https://install.python-poetry.org | %PYTHON%
  - cmd: poetry install
  - sh: curl -sSL https://install.python-poetry.org | python3 -
  - sh: sudo locale-gen en_US.UTF-8 && sudo locale-gen fr_FR.UTF-8
  - sh: echo $PATH
  - sh: poetry install


test_script:
  # Note that you must use the environment variable %PYTHON% to refer to
  # the interpreter you're using - Appveyor does not do anything special
  # to put the Python version you want to use on PATH.
  - cmd: pytest tests
  - sh: poetry run coverage run --source=mathmakerlib -m pytest -vv

after_test:
  # This step builds your wheels.
  - cmd: poetry build
  - sh: poetry run coveralls

artifacts:
  # bdist_wheel puts your built wheel in the dist directory
  - path: dist\*

#on_success:
#  You can use this step to upload your artifacts to a public website.
#  See Appveyor's documentation for more details. Or you can simply
#  access your wheels from the Appveyor "artifacts" tab for your build.
